id: P010404
initial_creation_type: ocr
source_metadata:
  id: bdr:W27307
  title: མུ་ལི་ཆོས་འབྱུང
  author: ''
  volumes:
    f7e61ceabab141d7abe2623387876878:
      image_group_id: I4269
      title: ''
      volume_number: 1
      total_pages: 263
